# Generated by Django 3.0.8 on 2020-07-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamiliarProgrammingLanguages',
            new_name='FamiliarProgrammingLanguage',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='ProficientProgrammingLanguages',
            new_name='ProficientProgrammingLanguage',
        ),
    ]
