# Generated by Django 3.0.8 on 2020-07-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200726_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
