# Generated by Django 3.0.8 on 2020-07-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_education_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='courses',
        ),
    ]
