# Generated by Django 3.0.8 on 2020-07-27 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200727_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=30)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Education')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
