# Generated by Django 3.0.8 on 2020-07-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200727_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='languages',
            new_name='language',
        ),
    ]
