# Generated by Django 3.0.8 on 2020-07-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200727_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
