# Generated by Django 3.0.8 on 2020-07-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200727_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='education',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ManyToManyField(to='cv.Education'),
        ),
    ]
