# Generated by Django 3.0.8 on 2020-07-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20200727_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.ManyToManyField(to='cv.Course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default='', max_length=30),
        ),
    ]
