# Generated by Django 3.0.8 on 2020-07-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20200727_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='course',
        ),
        migrations.AddField(
            model_name='education',
            name='courses',
            field=models.ManyToManyField(blank=True, to='cv.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(default='', max_length=60),
        ),
    ]
